In [1]:
import pandas as pd
import ast
import seaborn as sns
from matplotlib import pyplot as plt

In [2]:
df=pd.read_csv("/Users/MathildeStouby/Untitled Folder/tmdb_5000_movies.csv")

In [3]:
subset=df[['title','budget','revenue','genres','keywords','popularity','vote_average','vote_count','production_countries','release_date']]

In [4]:
subset=subset[subset.budget != 0]
subset=subset[subset.revenue != 0]

In [5]:
subset['overskud i procent'] = (subset.revenue/subset.budget)*100

In [6]:
countries=[]

for liste in subset['production_countries']:
    Temp = ast.literal_eval(liste)
    countries.append(Temp)

onlycountries=[]

for i in range(len(countries)):
    templist=[]
    for j in range(len(countries[i])):
        x = countries[i][j]["name"]
        templist.append(x)
    onlycountries.append(templist)

In [7]:
subset['produktionsland']=onlycountries
subset=subset.drop('production_countries',axis=1)

In [8]:
keywords=[]

for liste in subset['keywords']:
    Temp = ast.literal_eval(liste)
    keywords.append(Temp)

onlykeywords=[]

for i in range(len(keywords)):
    templist=[]
    for j in range(len(keywords[i])):
        x = keywords[i][j]['name']
        templist.append(x)
    onlykeywords.append(templist)

In [9]:
subset['nøgleord']=onlykeywords
subset=subset.drop('keywords',axis=1)

In [10]:
genres=[]

for liste in subset['genres']:
    Temp = ast.literal_eval(liste)
    genres.append(Temp)

onlygenres=[]

for i in range(len(genres)):
    templist=[]
    for j in range(len(genres[i])):
        x = genres[i][j]['name']
        templist.append(x)
    onlygenres.append(templist)

In [11]:
subset['genrer']=onlygenres
subset=subset.drop('genres',axis=1)

In [12]:
yes_or_no_USA=[]

for liste in subset.produktionsland:
    if "United States of America" in liste:
        yes_or_no_USA.append(1)
    else:
        yes_or_no_USA.append(0)

subset['USA']=yes_or_no_USA

In [13]:
subset=subset[subset.USA == 1]
subset=subset.drop('USA',axis=1)

In [14]:
listofgenres=['Drama',
 'Comedy',
 'Thriller',
 'Action',
 'Romance',
 'Adventure',
 'Crime',
 'Science Fiction',
 'Horror',
 'Family',
 'Fantasy',
 'Mystery',
 'Animation',
 'History',
 'Music',
 'War',
 'Documentary',
 'Western',
 'Foreign',
 'TV Movie']

In [15]:
i=0

while i<len(listofgenres):
    temp=[]
    for liste in subset.genrer:
        if listofgenres[i] in liste:
            temp.append(1)
        else:
            temp.append(0)
    subset[str(listofgenres[i])]=temp
    i+=1

In [16]:
subset

,title,budget,revenue,popularity,vote_average,vote_count,release_date,overskud i procent,produktionsland,nøgleord,...,Fantasy,Mystery,Animation,History,Music,War,Documentary,Western,Foreign,TV Movie
0,Avatar,237000000,2787965087,150.437577,7.2,11800,2009-12-10,1176.356577,"[United States of America, United Kingdom]","[culture clash, future, space war, space colon...",...,1,0,0,0,0,0,0,0,0,0
1,Pirates of the Caribbean: At World's End,300000000,961000000,139.082615,6.9,4500,2007-05-19,320.333333,[United States of America],"[ocean, drug abuse, exotic island, east india ...",...,1,0,0,0,0,0,0,0,0,0
2,Spectre,245000000,880674609,107.376788,6.3,4466,2015-10-26,359.459024,"[United Kingdom, United States of America]","[spy, based on novel, secret agent, sequel, mi...",...,0,0,0,0,0,0,0,0,0,0
3,The Dark Knight Rises,250000000,1084939099,112.312950,7.6,9106,2012-07-16,433.975640,[United States of America],"[dc comics, crime fighter, terrorist, secret i...",...,0,0,0,0,0,0,0,0,0,0
4,John Carter,260000000,284139100,43.926995,6.1,2124,2012-03-07,109.284269,[United States of America],"[based on novel, mars, medallion, space travel...",...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4758,The Signal,4000000,600896,27.662696,5.8,631,2014-03-15,15.022400,[United States of America],"[hacker, supernatural powers, road trip, indep...",...,0,0,0,0,0,0,0,0,0,0
4773,Clerks,27000,3151130,19.748658,7.4,755,1994-09-13,11670.851852,[United States of America],"[salesclerk, loser, aftercreditsstinger]",...,0,0,0,0,0,0,0,0,0,0
4788,Pink Flamingos,12000,6000000,4.553644,6.2,110,1972-03-12,50000.000000,[United States of America],"[gay, trailer park, pop culture, drug dealer, ...",...,0,0,0,0,0,0,0,0,0,0
4796,Primer,7000,424760,23.307949,6.9,658,2004-10-08,6068.000000,[United States of America],"[distrust, garage, identity crisis, time trave...",...,0,0,0,0,0,0,0,0,0,0
4798,El Mariachi,220000,2040920,14.269792,6.6,238,1992-09-04,927.690909,"[Mexico, United States of America]","[united states–mexico barrier, legs, arms, pap...",...,0,0,0,0,0,0,0,0,0,0